# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: 量潮RESTful API规范
author: 量潮科技

# Information about where the book exists on the web
repository:
  url: https://github.com/quanttide/quanttide-restful-api-specification # Online location of your book
  branch: master  # Which branch of the repository should be used when creating links (optional)
